### PR TITLE
Improvement: minimize & close to tray config options

### PR DESCRIPTION
**Pull request by Dude29**
Added config options to control the behavior of the minimize and close button.
The user can now choose whether the app minimizes or closes to the tray. 

Both these options are only valid when the user has enabled the tray icon using the config option `tray-icon` in the config file otherwise the minimize and close buttons assume the default Electron behavior which is to minimize and close the main window, respectively.

These options can be set in the config file(`~/.config/.todoist-linux.json`), for example:
```JSON

{
    "quit": "Alt+F4",
    "tray-icon": "icon.png",
    "minimize-to-tray": true,
    "close-to-tray": false
}
```
Tested **manually** on Ubuntu 20.04 using GNOME.

### CODE REVIEW

**Comment by tukusejssirs** [comment]
Nice work! But may I suggest to use a separate folder for Todoist? And better yet: implement the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), esp use `XDG_CONFIG_HOME` variable is set.

And I think that minimalisation and closing systray do not contradict each other, meaning that one could minimise the app with minimalisation button (or shortcut) and close to systray with th close button (or shortcut).

And It think that while keyboard shortcut customisation is nice to have, but one for quitting should be set system-wide (e.g. in the GNOME Settings).

I still need to test it out.

**Comment by KryDos** [comment]
@tukusejssirs completely agree with you on config file name (the leading dot in it). Unfortunately I made that mistake initially and I think now it too late to change it. People may get issues with it after the update. 
We could probably add one more config (the right one) and in case it is not exist then we can fallback to the current one (bad one). 
But I don't really like this, since it adds more code and more complexity to such a simple project. I guess this issue might be solved if/when the settings UI is implemented.

**Comment by tukusejssirs** [comment]
@KryDos, or you could deprecate the old config now and some time in the future, you can release an (API-)breaking/major release. While deprecating, you might do what you suggested (use the new config if it exists; if it does not exist, you the old config).

I agree that it might be resolved with the UI settings as it _might_ bring other breaking stuff. :smiley:

**Comment by KryDos** [comment]
excuse me guys I'm a bit delaying the merge of this awesome PR. Give me few more days and I'll review and merge it.

**Comment by mikkovedru** [comment]
@KryDos 
Any update?

**Comment by KryDos** [comment]
That was pretty slow from my side, once again guys, my apologies. Thanks @Dude29 for the implementation!

**Pull request merged**
