### PR TITLE
Fixed opening links in default browser

### LINKED ISSUE #124: URL in task name is opening in non-default-browser (Chromium)
* OS Linux Mint 20 Cinnamon (Based on Ubuntu 20.04)
* Cinnamon 4.6.7

I updated my OS from Mint 19.3 to Mint 20 and at the same time, I also updated all other programs, including todoist-linux (it has been some time since I last updated todoist-linux and I had to jump a few versions).

Now I noticed that the links that are in the task names are opening in a separate Chrome window (without address bar/menu/buttons/etc and without starting the main Chrome instance), instead of the default-browser Firefox. Pressing Ctrl or Shift together with clicking does not change the situation.

image

### PR DESCRIPTION
**Pull request by ceiphr**
Fixed https://github.com/KryDos/todoist-linux/issues/124 using the solution found [here](https://stackoverflow.com/a/59499271/9264137).

### CODE REVIEW

**Comment by bernd** [comment]
I tested this on Ubuntu 20.04 with a DEB package. It fixes the problem of links not opening in the default browser.

Thank you! :+1:

**Comment by KryDos** [comment]
Unfortunately this issue is a bit more complicated. The app itself has a bunch of links that can be treated as "internal" and must be opened in the same window. 
`Settings` for example and actually every link under that gear icon. 

Also the login screen. When user clicks on "login with google" we should open it in the same window and shouldn't use external browser. 

I believe we can detect if a link belongs to "todoist.com" domain and the we can open it internally in the app. Plus we may need to add some more exception links for oAuth links for google and facebook.

**Comment by ceiphr** [comment]
@KryDos Good point. I'll add those exceptions by the end of the week.

**Comment by ceiphr** [comment]
So, I just reverted some changes related to https://github.com/KryDos/todoist-linux/pull/123 and added the restrictions for login and Todoist URLs.

@KryDos can you see if opening settings is okay? It opens in electron, but seems to do it in an external window for whatever reason and I don't know why.

**Pull request closed without merging**
