### PR TITLE
Refactored main.js

### PR DESCRIPTION
**Pull request by ceiphr**
`main.js` is getting too big, especially with the new menuBar and tray entries. This PR refactors `main.js` into several smaller JS files. 

Specifically:
- Tray and menuBar get separate JS files
- customeUserAgent is now in `util.js`
- I couldn't find any place in the project where `handleRedirect` was being used, so I removed it.

I've also added a [Prettier](https://prettier.io/) config for standardizing file formatting. 

Since this PR is more subjective, please let me know if anything should be changed or reverted. Also, while I've done my own testing to find and resolve refactoring bugs, I still feel that other people should test out this PR to ensure there are no bugs.

### CODE REVIEW

**Comment by KryDos** [comment]
hey @ceiphr, 
thanks for the PR and my apologies for the delay in review. 

Could you please remove `.prettierrc` and I'll merge it. We definitely need to setup some codding rules but let's not do it in this PR.

**Comment by ceiphr** [comment]
Sounds good. I'll push a commit that removes it tonight.

**Comment by ceiphr** [comment]
@KryDos Is it okay if the formatting I added is kept, or should that also be reverted?

**Comment by KryDos** [comment]
@ceiphr the formatting is perfectly fine.

**Comment by ceiphr** [comment]
Perfect. Thank you for getting back to me so quickly.

**Comment by KryDos** [comment]
Merged. Thanks a lot!

**Pull request merged**
